# CI  de NÍVEL 1 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução manual'

# regras de execução (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch: 

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

    #passos do script de build
    steps:
      # Clone do projeto
      - uses: actions/checkout@v4

      # install node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # install yarn
      - name: Instalando o yarn
        run: npm install -g yarn

      # install dependencies
      - name: Instalando as dependencies
        run: yarn
      
      # Setup playwright
      - name: Instalando playwright
        run: yarn playwright install
      
      # executar os testes e2e
      - name: Executando os testes e2e
        run: yarn run e2e

      

